# -*- mode: ruby -*-
# vi: set ft=ruby :
if !Vagrant.has_plugin?("vagrant-docker-compose")
  puts "Pls install vagrant-docker-compose (vagrant plugin install vagrant-docker-compose), then try 'vagrant up' again"
    system("vagrant plugin install vagrant-docker-compose")
  exit
end 

if !Vagrant.has_plugin?("vagrant-disksize")
   puts "Pls install vagrant-disksize (vagrant plugin install vagrant-disksize), then try 'vagrant up' again"
   system("vagrant plugin install vagrant-disksize")
   puts "Dependencies installed, please try `vagrant up` again."
   exit
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/bionic64"
  config.disksize.size = "40GB"
  config.ssh.shell="bash"
  config.vm.provision "shell", path: "pre_init.sh", privileged: false
  config.vm.provision :docker
  config.vm.provision :docker_compose
  config.vm.provision "shell", inline: "apt-get update && apt-get install -y python-minimal"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision "shell", path: "init.sh", privileged: false
  # Fix https://github.com/hashicorp/vagrant/issues/10280
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
